export const pagesRoutes = [
  ["v-2d0a870d","/en/",{"y":"h","t":"qz‘s fancy House","i":"home"},["/en/README.md"]],
  ["v-2d0a870d","/en/",{"y":"h","t":"qz‘s fancy House","i":"home"},["/en/README.md"]],
  ["v-5aa3d8ba","/en/intro.html",{"y":"a","t":"Personal Introduction","i":"profile"},[":md"]],
  ["v-6fc41603","/en/programming/",{"y":"h","t":"Column-progamming","i":"zhongduan"},["/en/programming/README.md"]],
  ["v-f8ddd8c4","/zh/programming/",{"y":"h","t":"Column-progamming","i":"zhongduan"},["/zh/programming/README.md"]],
  ["v-1112b946","/zh/programming/webpage-making.html",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},[":md"]],
  ["v-bcae749a","/zh/programming/python/Final-Spirit(basic).html",{"y":"a","t":"python期末冲刺","i":"bijiben1"},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-54652975","/zh/programming/python/",{"y":"p","t":"Python"},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"Category","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"Tag","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"Articles","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"Star","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"Timeline","I":0},[]],
  ["v-fbb94a6e","/zh/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-540234fd","/zh/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-54d7ff21","/zh/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-2c3ee7f5","/zh/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-27b02be6","/zh/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-f910a1ec","/zh/category/%E7%BD%91%E7%AB%99%E5%88%B6%E4%BD%9C/",{"y":"p","t":"网站制作 分类","I":0},["/zh/category/网站制作/"]],
  ["v-4280e556","/zh/tag/%E7%BD%91%E7%AB%99%E5%88%B6%E4%BD%9C/",{"y":"p","t":"标签: 网站制作","I":0},["/zh/tag/网站制作/"]],
  ["v-56961c9f","/zh/column/accumulating/",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},["/zh/column/accumulating/README.md"]],
  ["v-947048fc","/zh/column/accumulating/Month/2023.8.html",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},[":md"]],
  ["v-928c4332","/zh/column/accumulating/Year/2023.html",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},[":md"]],
  ["v-b7c2f0b4","/zh/column/accumulating/Day/2023.8/2023.8.24.html",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},[":md"]],
  ["v-540d0773","/zh/column/about-me/intro.html",{"y":"a","t":"个人介绍","i":"profile"},[":md"]],
  ["v-725d0d4a","/zh/column/skill-sharing/programming/python/Final-Spirit(basic).html",{"y":"a","t":"python期末冲刺","i":"bijiben1"},[":md"]],
  ["v-342da8ee","/zh/column/skill-sharing/programming/webpage-making.html",{"y":"a","t":"制作网页的笔记整理","i":"bijiben1"},[":md"]],
  ["v-561a34f6","/zh/column/skill-sharing/programming/",{"y":"h","t":"Column-progamming","i":"zhongduan"},["/zh/column/skill-sharing/programming/README.md"]],
]
